title: Deep Image Spatial Transformation <br> for Person Image Generation
description: Yurui Ren, Xiaoming Yu, Junming Chen, Thomas H. Li, Ge Li <br> CVPR 2020
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman